### ISSUE TITLE
General: future plans for amcharts/amcharts3-angular2

### ISSUE THREAD

**Issue by ryzy** [amcharts/amcharts3-angular2#19]
Hi,

I have a few question regarding *amcharts3-angular2* in general. How seriously are you committed to providing a nice wrapper for AmCharts for Angular >= 2? I like the initiative and I like that the author behind it is an official AmChart company. On the other side, this package needs more attention to be considered as a production-grade.

Couple of things I have in mind:
* NPM package in registry is needed - see #18
* AoT ready (#15 is probably related to that) - probably we'd need to add some simple build process to that
* currently no tests whatsoever, so we'd need to add some. Plus some CI setup (travis or circle ci would do)
* the package could be probably renamed to `amcharts3-angular`, since we expect new major version of Angular every quarter or so?

Since we rely on AmCharts in our organisation quite heavily and we develop with Angular, if you say you're OK with the above, we might come back with couple PRs :)

Best, Marcin

**Comment by Pauan** [comment]
@ryzy I'm sorry for the late reply, I'm the only developer for the amcharts3-angular2 plugin, and I've been busy with other projects. In a couple weeks I'll be able to devote more time to this plugin.

We are very committed to supporting Angular with AmCharts v4.

As for this plugin (which is for AmCharts v3), the support isn't as good, but we'll support it as much as we can until v4 is released.

Publishing an NPM package is something I want to do, but I'll need to coordinate it with the rest of the AmCharts team.

This plugin pre-compiles a `.js` file called `index.js`, is there anything else we need to do?

Unit tests are a great idea, but I don't think they would be very helpful for v3, because v3 will soon be obsoleted by v4.

Renaming the package is also a good idea, but it would break all existing code which uses this package.

I don't use Angular 2, so my experience with it is quite low. PRs are much appreciated!

**Comment by codegastudio** [comment]
Any idea of the AmCharts v4 release date ?

**Comment by ryzy** [comment]
Hi @Pauan, thanks for your reply!

> We are very committed to supporting Angular with AmCharts v4.

Glad to hear that, will be watching this repo for updates :D

> Publishing an NPM package is something I want to do, but I'll need to coordinate it with the rest of the AmCharts team.

Let me know what are the plans, I can help here.

> This plugin pre-compiles a .js file called index.js, is there anything else we need to do?

Yeah, see #29 for example. We need at least .d.ts and .metadata.json to support AoT. Perhaps we could add .umd as well for people who don't use webpack/systemjs.

> Unit tests are a great idea, but I don't think they would be very helpful for v3, because v3 will soon be obsoleted by v4.
> Renaming the package is also a good idea, but it would break all existing code which uses this package.

Breaking change is of course not what we want. But we could mark this package as obsolete and create new one. Otherwise you'll end up with big confusion: angular2 in the name suggest angular 2 (while now we have angular 4 and next), amchart3 in the name suggest v3, while we'll have v4 soon. Something like `ngx-amcharts` would do perhaps better :D

**Comment by Pauan** [comment]
@codegastudio The current plan is to release v4 before next year.

@ryzy I doubt that we'll be using this repository for v4, instead we'll likely do something else, but I'll think about it.

**Comment by Pauan** [comment]
Most of these issues have been fixed, so I'm going to close this now.

Feel free to create more issues if additional changes are needed.
