### ISSUE TITLE
Integration of amcharts3-angular2 imposible with official angular/quickstart.git

### ISSUE THREAD

**Issue by noisy** [amcharts/amcharts3-angular2#24]
There is a official "QuickStart seed" repository for angular2, mentioned on official website in few places:

https://angular.io/docs/ts/latest/guide/setup.html

QuickStart seed is used by many users as a basic template to start project with angular 2. Possibility of easy integration amcharts3-angular2 with Angular 2 QuickStart seed in my opinion, should have very high priority.

Unfortunately integration done according to rules from https://github.com/amcharts/amcharts3-angular2 gives result unsuccessful:

![selection_751](https://cloud.githubusercontent.com/assets/201263/24461765/74ea9b38-14a2-11e7-8e3d-31ef5495eb3d.png)

## Oryginal QuickStart code with amcharts3-angular2

https://github.com/noisy/quickstart/pull/1/files

## Logs from npm:
https://gist.github.com/noisy/2f9863c30d3bcfc9873754b8e9128f82#file-gistfile1-txt-L70

**Comment by Pauan** [comment]
Hi Krzysztof,

I have changed [the instructions](https://github.com/amcharts/amcharts3-angular2#how-to-use) so that they are now compatible with the QuickStart seed.

In addition to following the normal instructions, you must also add `amcharts3-angular2` to your `src/system.config.js` file, like this:

```js
System.config({
  map: {
    'amcharts3-angular2': 'node_modules/amcharts3-angular2/index.js'
  }
});
```

I also added a [working QuickStart seed example](https://github.com/amcharts/amcharts3-angular2/tree/master/examples/quickstart).
