### ISSUE TITLE
Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by Abhishek679** [amcharts/amcharts3-angular2#61]
Hello @Pauan 
i'm trying to use polar amchart in my project. but i think it is not supported
can u please suggest me.
thank you.

**Comment by Pauan** [comment]
@Abhishek679 All chart types are supported. Make sure that you are using the correct `<script>` tags in your `index.html` file:

```html
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/radar.js"></script>
```

Also, even though they are called "polar charts", you must use a `type` of `"radar"`:

```typescript
this.chart = this.AmCharts.makeChart("chartdiv", {
  "type": "radar",
  ...
});
```

If that doesn't solve the problem, please tell me what version of `@amcharts/amcharts3-angular` you are using.

**Comment by Abhishek679** [comment]
yes it will be worked.
thank you for helping

**Comment by Inframatic** [comment]
@Pauan Hey, I had the same problem and the problem persisted after implementing your solution.
I am using "amcharts3": "^3.21.13",

Are there any versions that you recommend over this?

I should also note that since this uses a wrapper and the script tags werent being read in my index file, that I was forced to make definition files for all chart types 

`import * as _AmSerialChart from 'amcharts3/amcharts/serial';

export const AmSerialChart = _AmSerialChart;`

**Comment by Pauan** [comment]
@Inframatic We only support loading V3 with `<script>` tags (V3 is very old, so it wasn't designed for npm).

However, [our V4 beta](https://www.amcharts.com/docs/v4/) is out, and it has excellent support for npm, TypeScript, and Angular.

I'm not sure why adding in `@Input` would cause that error. Have you tried inserting a `console.log(this.type, this.theme)` to verify that the properties are defined and with the correct values?

Also, could you please share your full code in a CodePen, Gist, or Git repo, so I can take a look?
